version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: roomy-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: roomy_db
      MYSQL_USER: roomy_user
      MYSQL_PASSWORD: roomy_password
      MYSQL_ROOT_PASSWORD: roomy_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - roomy-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: roomy-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: roomy_user
      PMA_PASSWORD: roomy_password
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - roomy-network

volumes:
  mysql_data:

networks:
  roomy-network:
    driver: bridge