server:
  port: 8080

spring:
  application:
    name: roomy-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/roomy
    username: root
    password: poasword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:realakshatjain@gmail.com}
    password: ${MAIL_PASSWORD:lziagmfijxyvkscn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:9f218785d47dc487a8cc06b262ef369c617a287e420e05f072c50acc6398e312}
  expiration: 86400000 # 24 hours in milliseconds

# Cloudinary Configuration
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dqywabxbo}
  api-key: ${CLOUDINARY_API_KEY:241963512481671}
  api-secret: ${CLOUDINARY_API_SECRET:2Rqtiy4YJ0ijINxOAMMGCvbuVuA}

# OTP Configuration
otp:
  expiration: 300000 # 5 minutes in milliseconds

logging:
  level:
    com.roomy: DEBUG
    org.springframework.security: DEBUG