server:
  port: 8080

spring:
  application:
    name: roomy-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/roomy_db
    username: roomy_user
    password: roomy_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:test@gmail.com}
    password: ${MAIL_PASSWORD:test-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

# Cloudinary Configuration (Use your own credentials)
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:demo-cloud}
  api-key: ${CLOUDINARY_API_KEY:demo-key}
  api-secret: ${CLOUDINARY_API_SECRET:demo-secret}

# OTP Configuration
otp:
  expiration: 300000 # 5 minutes

logging:
  level:
    com.roomy: DEBUG
    org.springframework.security: INFO