spring:
  application:
    name: roomy

  datasource:
    url: jdbc:mysql://localhost:3306/roomy
    username: akshat
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8000

logging:
  level:
    org:
      hibernate: DEBUG
      springframework: DEBUG

security:
  basic:
    enable: false
  secret: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"
  ignored: /**


#  docker run --name roomy-mysql -e MYSQL_DATABASE=roomy -e MYSQL_USER=akshat -e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=rootpassword -p 3306:3306 -d mysql
